previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: undb
    env: docker
    repo: https://github.com/vsposato/undb.git
    region: Ohio, USA
    plan: standard
    rootDir: .
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_UNDB_ADMIN_EMAIL
        value: vincent.sposato@gmail.com
      - key: PUBLIC_UNDB_ADMIN_PASSWORD
        value: D3c1s10n9148!
      - key: PUBLIC_UNDB_IS_DEMO
        value: 'true'
      - key: PUBLIC_UNDB_ANALYTICS_DOMAIN
        value: undb-app.2brosdevelopment.com
      - key: UNDB_SEED
        value: 'true'
    domains:
      - undb-app.2brosdevelopment.com
